name: foss4g
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - ghp-import
  - xarray
  - pip:
    - wget
    - sphinx-exercise
    - kerchunk==0.0.7
    - jupytext
    - nbgitpuller